### PR TITLE
final update for PW3

### PR DESCRIPTION
**Pull request by Manfred62**
final update of german language for ProcessWire 3

### CODE REVIEW

**Comment by yellowled** [comment]
@Manfred62 Thanks again for your huge, tireless efforts!

**Comment by tbba** [comment]
Do you want to include strings for 3rd party modules? I have code for croppable3 ready.

**Comment by yellowled** [comment]
@tbba We – @Manfred62 and I – had that discussion some time ago. My opinion is that it is not ideal for people who do not use said third party modules. I'm not sure if it actually would be an issue, but it feels bloaty and seems to make the language pack harder to maintain.

However, @Manfred62 has a repository for [3rd-party modules](https://github.com/Manfred62/pw-modules-lang-de) – not sure how actively maintained that is, though.

**Comment by tbba** [comment]
OK, sounds reasonable.

**Pull request merged**
